[package]
authors = ["Hayato Ito <hayato@google.com>"]
description = "WebBundle library"
edition = "2021"
license = "Apache-2.0"
name = "webbundle"
readme = "../README.md"
repository = "https://github.com/google/webbundle"
version = "0.1.4"

[dependencies]
url = "2.1.1"
anyhow = "1.0.26"
log = "0.4.8"
cbor_event = "2.1.3"
chrono = "0.4.10"
mime_guess = "2.0.1"
walkdir = "2.3.1"
pathdiff = "0.1.0"
http = "0.2.0"
headers = "0.3.1"
tokio = { version = "0.2", features = ["fs", "macros"] }
